# Generated by Django 4.0.1 on 2022-01-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
