# Generated by Django 4.0.1 on 2022-01-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickName',
            field=models.CharField(max_length=20),
        ),
    ]
